### ISSUE TITLE
net.ipv4.tcp_tw_recycle

### ISSUE THREAD

**Issue by t0d0r** [jonzobrist/Bash-Admin-Scripts#1]
Hi, 

Please, remove net.ipv4.tcp_tw_recycle=1 from the script, check there:
https://vincent.bernat.im/en/blog/2014-tcp-time-wait-state-linux

and thanks for the script!

Regards,
Todor

**Comment by jonzobrist** [comment]
Thanks! 
I've removed the dangerous/deprecated tcp_tw_recycle and added the safe tcp_tw_reuse
